name: aur-publish

on:
  release:
    types: [created]

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    env:
      PKGBUILD: aur/PKGBUILD
    steps:
      - uses: actions/checkout@v2

      - run: |
          echo 'Modifying ${{ env.PKGBUILD }} with new version'
          export pkgver=${{ github.event.release.tag_name }}
          export PKGBUILD_CONTENT=`cat ${{ env.PKGBUILD }}`
          echo pkgver="${pkgver:1}" > '${{ env.PKGBUILD }}'
          echo "$PKGBUILD_CONTENT" >> '${{ env.PKGBUILD }}'

      - uses: KSXGitHub/github-actions-deploy-aur@v2.5.0
        with:
          pkgname: yues
          pkgbuild: ${{ env.PKGBUILD }}
          commit_username: github-actions[bot]
          commit_email: 41898282+github-actions[bot]@users.noreply.github.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519

      - run: |
          echo 'Reset ${{ env.PKGBUILD }} changes'
          git checkout HEAD -- '${{ env.PKGBUILD }}'
